/**************************************/
/******* Name   : Mahmoud Rajab *******/
/******* Date   :  25/8/2020    *******/
/******* SWC    :    PORT       *******/
/******* Version:    1.0        *******/
/**************************************/
#ifndef PORT_PRIVATE_H
#define PORT_PRIVATE_H

#define INPUT     0
#define OUTPUT    1

#define HIGH      1
#define LOW       0

#define CONC(b7,b6,b5,b4,b3,b2,b1,b0)           CONC_HELBER(b7,b6,b5,b4,b3,b2,b1,b0)
#define CONC_HELBER(b7,b6,b5,b4,b3,b2,b1,b0)    0b##b7##b6##b5##b4##b3##b2##b1##b0

#define PORTA_DIR                 CONC(PORTA_PIN7_DIR,PORTA_PIN6_DIR,PORTA_PIN5_DIR,PORTA_PIN4_DIR,PORTA_PIN3_DIR,PORTA_PIN2_DIR,PORTA_PIN1_DIR,PORTA_PIN0_DIR)
#define PORTB_DIR                 CONC(PORTB_PIN7_DIR,PORTB_PIN6_DIR,PORTB_PIN5_DIR,PORTB_PIN4_DIR,PORTB_PIN3_DIR,PORTB_PIN2_DIR,PORTB_PIN1_DIR,PORTB_PIN0_DIR)
#define PORTC_DIR                 CONC(PORTC_PIN7_DIR,PORTC_PIN6_DIR,PORTC_PIN5_DIR,PORTC_PIN4_DIR,PORTC_PIN3_DIR,PORTC_PIN2_DIR,PORTC_PIN1_DIR,PORTC_PIN0_DIR)
#define PORTD_DIR                 CONC(PORTD_PIN7_DIR,PORTD_PIN6_DIR,PORTD_PIN5_DIR,PORTD_PIN4_DIR,PORTD_PIN3_DIR,PORTD_PIN2_DIR,PORTD_PIN1_DIR,PORTD_PIN0_DIR)


#define PORTA_INTIAL_VALUE        CONC(PORTA_PIN7_INTIAL_VALUE,PORTA_PIN6_INTIAL_VALUE,PORTA_PIN5_INTIAL_VALUE,PORTA_PIN4_INTIAL_VALUE,PORTA_PIN3_INTIAL_VALUE,PORTA_PIN2_INTIAL_VALUE,PORTA_PIN1_INTIAL_VALUE,PORTA_PIN0_INTIAL_VALUE)
#define PORTB_INTIAL_VALUE        CONC(PORTB_PIN7_INTIAL_VALUE,PORTB_PIN6_INTIAL_VALUE,PORTB_PIN5_INTIAL_VALUE,PORTB_PIN4_INTIAL_VALUE,PORTB_PIN3_INTIAL_VALUE,PORTB_PIN2_INTIAL_VALUE,PORTB_PIN1_INTIAL_VALUE,PORTB_PIN0_INTIAL_VALUE)
#define PORTC_INTIAL_VALUE        CONC(PORTC_PIN7_INTIAL_VALUE,PORTC_PIN6_INTIAL_VALUE,PORTC_PIN5_INTIAL_VALUE,PORTC_PIN4_INTIAL_VALUE,PORTC_PIN3_INTIAL_VALUE,PORTC_PIN2_INTIAL_VALUE,PORTC_PIN1_INTIAL_VALUE,PORTC_PIN0_INTIAL_VALUE)
#define PORTD_INTIAL_VALUE        CONC(PORTD_PIN7_INTIAL_VALUE,PORTD_PIN6_INTIAL_VALUE,PORTD_PIN5_INTIAL_VALUE,PORTD_PIN4_INTIAL_VALUE,PORTD_PIN3_INTIAL_VALUE,PORTD_PIN2_INTIAL_VALUE,PORTD_PIN1_INTIAL_VALUE,PORTD_PIN0_INTIAL_VALUE)

#endif